config/routes.rb
Quips::Application.routes.draw do
  resources :api_keys
  resources :quips do
    post :vote
    collection do
      get :api_info
      get :ajax_autocomplete
    end
  end

  root :to => "quips#index"

end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
end

app/models/quip.rb
class Quip < ActiveRecord::Base
  cattr_reader :per_page, :sortable_columns, :sort_directions
  @@per_page = 25
  @@sortable_columns = ["votes", "date", "id"]
  @@sort_directions = ["asc", "desc"]

  include Tire::Model::Search
  include Tire::Model::Callbacks

  validates_presence_of :quip

  def as_json(options = {})
    if options[:type] == :autocomplete 
      {:label => quip, :value => id}
    end
  end
end

app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  before_filter :check_admin_mode, :only => [:index, :destroy]

  def check_admin_mode
    unless false #i'm a hacky hacky switch!
      redirect_to :back 
    end
  end

  # GET /api_keys
  # GET /api_keys.xml
  def index
    @api_keys = ApiKey.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @api_keys }
    end
  end

  # GET /api_keys/1
  # GET /api_keys/1.xml
  def show
    @api_key = ApiKey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @api_key }
    end
  end

  # GET /api_keys/new
  # GET /api_keys/new.xml
  def new
    @api_key = ApiKey.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @api_key }
    end
  end

  # POST /api_keys
  # POST /api_keys.xml
  def create
    @api_key = ApiKey.new(params[:api_key])
    @api_key.key = Digest::SHA1.hexdigest params[:api_key][:username]

    respond_to do |format|
      if @api_key.save
        flash[:notice] = 'ApiKey was successfully created.'
        format.html { redirect_to(@api_key) }
        format.xml  { render :xml => @api_key, :status => :created, :location => @api_key }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @api_key.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /api_keys/1
  # PUT /api_keys/1.xml
  def update
    @api_key = ApiKey.find(params[:id])

    respond_to do |format|
      if @api_key.update_attributes(params[:api_key])
        flash[:notice] = 'ApiKey was successfully updated.'
        format.html { redirect_to(@api_key) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @api_key.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /api_keys/1
  # DELETE /api_keys/1.xml
  def destroy
    @api_key = ApiKey.find(params[:id])
    @api_key.destroy

    respond_to do |format|
      format.html { redirect_to(api_keys_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time

  # See ActionController::RequestForgeryProtection for details
  # Uncomment the :secret if you're not using the cookie session store
  protect_from_forgery # :secret => 'ff21b85f816f796d5fca59f9594854b3'
  
  # See ActionController::Base for details 
  # Uncomment this to filter the contents of submitted sensitive data parameters
  # from your application log (in this case, all fields with names like "password"). 
  # filter_parameter_logging :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/quips_controller.rb
class QuipsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => :create
  # GET /quips
  # GET /quips.xml
  def index
    sort = params[:sort] || session[:sort] || 'newest'
    order = case sort
            when "votes"
              'votes desc'
            when "newest"
              'created_at desc'
            when "oldest"
              'created_at asc'
            end
    sort_changed = sort != session[:sort]
    @quips = Quip.order(order).page(params[:page]).per(15)
    session[:sort] = sort

    respond_to do |format|
      format.html # index.html.erb
      format.js { 
        # If the sort has changed, re-render from page 1; otherwise, 
        # show the next page of results
        js_view_to_render = sort_changed ? :index : :next_page
        @quips.any? ? render(js_view_to_render) : head(:not_found) 
      }
      format.xml  { render :xml => @quips }
    end
  end

  def ajax_autocomplete
    @term = params[:term]
    @results = Quip.search("#{@term}*")
    respond_to do |format|
      format.json { render :json => @results.as_json(:type => :autocomplete) }
    end
  end

  # GET /quips/1
  # GET /quips/1.xml
  def show
    if params[:id] == "random" then
      @quip = Quip.find(:first, :offset => rand(Quip.count))
    else
      @quip = Quip.find(params[:id])
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @quip }
    end
  end

  # GET /quips/new
  # GET /quips/new.xml
  def new
    @quip = Quip.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @quip }
    end
  end

  # GET /quips/1/edit
  def edit
    @quip = Quip.find(params[:id])
  end

  # POST /quips
  # POST /quips.xml
  def create
    params[:quip][:votes] = 0
    @quip = Quip.new(params[:quip])
    should_save = false
    if params[:apikey]
      key = ApiKey.find_by_key(params[:apikey])
      if key
        params[:quip][:submitter] = key.username
        should_save = true
      end
    else
      should_save = verify_recaptcha(@quip)
    end

    respond_to do |format|
      if should_save and @quip.save
        flash[:notice] = 'Quip was successfully created.'
        format.html { redirect_to(@quip) }
        format.xml  { render :xml => @quip, :status => :created, :location => @quip }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @quip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /quips/1
  # PUT /quips/1.xml
  def update
    @quip = Quip.find(params[:id])

    respond_to do |format|
      if @quip.update_attributes(params[:quip])
        flash[:notice] = 'Quip was successfully updated.'
        format.html { redirect_to(@quip) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @quip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /quips/1
  # DELETE /quips/1.xml
  def destroy
    @quip = Quip.find(params[:id])
    @quip.destroy

    respond_to do |format|
      format.html { redirect_to(quips_url) }
      format.xml  { head :ok }
    end
  end
  def vote
    if params[:type] == "up" 
      Quip.increment_counter(:votes, params[:id]) 
    elsif params[:type] == "down"
      Quip.decrement_counter(:votes, params[:id]) 
    end
    render :text => Quip.find(params[:id]).votes
  end

  def api_info
  end

  private
  def verify_recaptcha(*args)
    if Rails.env.test?
      true
    else
      super(*args)
    end
  end
end

app/helpers/api_keys_helper.rb
module ApiKeysHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quips_helper.rb
module QuipsHelper
end

app/views/api_keys/index.html.erb
<h1>Listing api_keys</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Key</th>
  </tr>

<% @api_keys.each do |api_key| %>
  <tr>
    <td><%=h api_key.username %></td>
    <td><%=h api_key.key %></td>
    <td><%= link_to 'Show', api_key %></td>
    <td><%= link_to 'Edit', edit_api_key_path(api_key) %></td>
    <td><%= link_to 'Destroy', api_key, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New api_key', new_api_key_path %>

app/views/api_keys/new.html.erb
<h1>New api_key</h1>

<%= form_for(@api_key) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', api_keys_path %>

app/views/api_keys/show.html.erb
<p>
  <b>Username:</b>
  <%=h @api_key.username %>
</p>

<p>
  <b>Key:</b>
  <%=h @api_key.key %>
</p>


<%= link_to 'Edit', edit_api_key_path(@api_key) %> |
<%= link_to 'Back', api_keys_path %>

app/views/layouts/api_keys.html.haml
!!!
%html{:lang => "en", "xml:lang" => "en", :xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html;charset=UTF-8", "http-equiv" => "content-type"}/
    %title
      ApiKeys: #{controller.action_name}
    = stylesheet_link_tag 'scaffold'
  %body
    %p{:style => "color: green"}= flash[:notice]
    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html;charset=UTF-8", "http-equiv" => "content-type"}/
    %title
      Quips: #{controller.action_name}
    = stylesheet_link_tag "application"
    = yield :page_head
    %title Quips
    = csrf_meta_tag
  %body
    .container
      = render :partial => "quips_header"
      = yield

    = javascript_include_tag "application"
    = yield :javascript

app/views/quips/_form.html.haml
= form_for(@quip) do |f|
  = f.label :source
  = f.text_field :source
  = f.label :submitter
  = f.text_field :submitter
  = f.label :date
  = f.text_field :date, class: 'datepicker'
  = f.label :quip
  = f.text_area :quip, size: '50x7'
  - if @quip.new_record?
    = recaptcha_tags
  = f.submit

app/views/quips/_quip.html.haml
%span.quip_display
  = link_to "\##{quip.id}", quip
  <span id=#{h "plus#{quip.id}"}>
  \#{link_to "+",  {:controller => :quips, :id => quip.id, :type => 'up'}, :remote => true}
(
%span{:id => "vote_#{quip.id}"}>= h quip.votes
)
<span id=#{h "minus#{quip.id}"}>#{link_to "-",  {:controller => :quips, :id => quip.id, :type => 'down'}, :remote => true}
.quip_display
  %pre= quip.quip

app/views/quips/_quips_header.haml
#index_header.navbar.clearfix
  %a.brand{href: quips_path} WHAT YOU SAY???
  %ul.nav
    %li#addnew
      = link_to new_quip_path do
        %span#addnew_plus +
        add quip
    %li#random
      = link_to quip_path('random') do
        %span#random_O O
        random
    %li
      = link_to 'api info', '/quips/api_info'
  %form.navbar-search.pull-right
    %input.search-query{:tabindex => "0", :placeholder => 'Search', :type => 'search'}
    #results{:style => "display:none;"}

app/views/quips/api_info.html.haml
%div
  %h2 Quips API
  %ol
    %li
      = link_to 'Create', :controller => 'api_keys', :action => 'new'
      an API key
    %li
      Send a POST request with the following keys and information:
      %ul
        %li Post to: http://stillraging.net/resquip/quips
        %li apikey = (your API key)
        %li quip[date] = MM-DD-YY (optional)
        %li quip[quip] = (quip string here)
    %li ...
    %li Profit!
  You can test the string using curl, like so:
  %pre
    curl -d "apikey=(api key)&amp;quip[date]=2010-05-12&amp;quip[quip]=testing;" #{quips_url}

app/views/quips/edit.html.haml
%h1 Editing quip
= render :partial => 'form'
= link_to 'Show', @quip
|
\#{link_to 'Back', quips_path}

app/views/quips/index.html.haml
#quip_list{'ng-app' => true}
  #sort_options
    = link_to 'Highest Rated', {:controller => :quips, :sort => :votes}, :remote => true, :id => 'sort_votes', :class => ('selected' if session[:sort] == 'votes')
    = link_to 'Newest', {:controller => :quips, :sort => :newest}, :remote => true, :id => 'sort_newest', :class => ('selected' if session[:sort] == 'newest' || session[:sort].blank?)
    = link_to 'Oldest', {:controller => :quips, :sort => :oldest}, :remote => true, :id => 'sort_oldest', :class => ('selected' if session[:sort] == 'oldest')
  #listing
    = render :partial => "quip", :collection => @quips

app/views/quips/index.js.erb
$('#listing').fadeOut(250, function() {
  $('#listing').html('<%= escape_javascript(render :partial => 'quip.html.haml', :collection => @quips) %>');
  quips_scroller['page'] = 1;
  quips_scroller['loading'] = false;
  $('#sort_options a').removeClass('selected');
  $('#sort_options a#sort_<%= session[:sort] %>').addClass('selected');
  $('#listing').show();
  window.scrollTo(0,0);
});

app/views/quips/new.html.haml
%h1 New quip
= render :partial => 'form'
= link_to 'Back', quips_path

app/views/quips/next_page.js.erb
$('#listing').append('<%= escape_javascript(render :partial => 'quip.html.haml', :collection => @quips) %>');

app/views/quips/show.html.haml
%p
  %b Source:
  = h @quip.source
%p
  %b Submitter:
  = h @quip.submitter
%p
  %b Date:
  = h @quip.date
%p
  %b Score:
  %span#votes= h @quip.votes
  %span#upvote
    = link_to "Upvote",                                        |
      {:controller => :quips, :id => @quip.id, :type => 'up'}, |
      :remote => true                                          |
  %span#downvote
    = link_to "Downvote",                                        |
      {:controller => :quips, :id => @quip.id, :type => 'down'}, |
      :remote => true                                            |
.quip_text
  = @quip.quip
= link_to 'Edit', edit_quip_path(@quip)
|
\#{link_to 'Back', quips_path}